
name: Test Agent

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Docker Compose
        run: |
          echo "Starting Docker Compose..."
          docker-compose up -d
          docker-compose ps

      - name: Verify Containers are Running
        run: |
          echo "Verifying containers are running..."
          if [ $(docker-compose ps -q | wc -l) -eq 0 ]; then
            echo "No containers are running."
            exit 1
          fi
          echo "Containers are running successfully."

      - name: Cleanup
        run: |
          echo "Cleaning up..."
          docker-compose down
