version: '3.8'
services:
  discord-bot:
    build: .
    container_name: discord-bot
    env_file: .env  # Load environment variables from .env file
    volumes:
      - .:/usr/src/app
    networks:
      - pr-cybr-net
    ports:
      - "8080:80"  # Map Nginx port to host if needed
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - pr-cybr-net
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  pr-cybr-net:
    driver: bridge

volumes:
  mongo_data: