name: maintenance

on:
  workflow_dispatch:   # manual trigger
  schedule:            # optional: run daily at 02:00 UTC
    - cron: "0 2 * * *"
  push:
    branches: [ codex, agents, dev ]
  pull_request:
    branches: [ main ]

jobs:
  maintenance:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Install dependencies
        run: |
          # Retry logic for apt-get operations to handle transient network issues
          for i in 1 2 3; do
            echo "Attempt $i: Updating package lists..."
            apt-get update -y && break || {
              echo "Update failed, retrying in 5 seconds..."
              sleep 5
            }
          done
          
          # Install with retry logic and --fix-missing flag
          for i in 1 2 3; do
            echo "Attempt $i: Installing dependencies..."
            apt-get install -y --fix-missing git python3 python3-pip && break || {
              echo "Installation failed, retrying in 5 seconds..."
              sleep 5
              apt-get update -y
            }
          done

      - name: Clone repo
        run: |
          git clone https://github.com/${{ github.repository }} /workspace

      - name: Run maintenance.py if present
        run: |
          cd /workspace
          if [ -f maintenance.py ]; then
            echo "🔧 Running maintenance script..."
            python3 maintenance.py
          else
            echo "⚠️ No maintenance.py found, skipping."
          fi
