name: Notion Sync

on:
  issues:
    types: [opened, edited, reopened, labeled, unlabeled, closed]
  pull_request:
    types: [opened, edited, reopened, labeled, unlabeled, closed, converted_to_draft, ready_for_review, synchronize]
  discussion:
    types: [created, edited, answered, unanswered, labeled, unlabeled]
  project_card:
    types: [created, edited, moved, converted, deleted]
  workflow_run:
    workflows:
      - "Dev Branch Workflow"
      - "Stage Branch Workflow"
      - "Production Branch Workflow"
    types:
      - completed

permissions:
  contents: read
  issues: read
  pull-requests: read
  discussions: read
  projects: read

jobs:
  notion-sync:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_TASKS: ${{ secrets.NOTION_DATABASE_TASKS }}
      NOTION_DATABASE_ISSUES: ${{ secrets.NOTION_DATABASE_ISSUES }}
      NOTION_DATABASE_PULL_REQUESTS: ${{ secrets.NOTION_DATABASE_PULL_REQUESTS }}
      NOTION_DATABASE_DISCUSSIONS: ${{ secrets.NOTION_DATABASE_DISCUSSIONS }}
      NOTION_DATABASE_PROJECTS: ${{ secrets.NOTION_DATABASE_PROJECTS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
