name: tfc-sync

on:
  push:
    branches:
      - codex     # AI-driven commits (Codex Platform)
      - agents    # Agent-driven inter-repo commits
  pull_request:
    branches:
      - main      # All PRs targeting main branch (HITL control)

permissions:
  contents: read
  id-token: write   # Prepares for Terraform Cloud OIDC auth

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AGENT_ACTIONS }}   # PAT stored in TFC

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Run plan for validation (always runs)
      - name: Terraform Plan
        run: terraform plan -input=false -no-color

      # Only apply if PR merged into main
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
